### ISSUE TITLE
blur effect are gone after upgrade to master flutter 

### ISSUE THREAD

**Issue by lucasjinreal** [fluttercandies/ripple_backdrop_animate_route#1]
From the lastest flutter master channel on, the blur effect of this lib are gone.

@fluttercandies would u help to have a look and fix? This is a very good lib

**Comment by AlexV525** [comment]
Is it still working on the stable channel? We don't usually guarantee that master will work as intended, but I'll check it later.

**Comment by lucasjinreal** [comment]
@AlexV525  I don't know why I switched to master branch of flutter, oh, it's a bug in stable but fixed in master, however I reported this mean it might happen in the near future.

If you guys can check on master, that would be great! Hopfully there can be a fix for master branch, this blur effect is very important

**Comment by AlexV525** [comment]
It's good to go.
