### ISSUE TITLE
升级Flutter版本后，iOS端BackdropFilter无效

### ISSUE THREAD

**Issue by rquanx** [fluttercandies/ripple_backdrop_animate_route#2]
Flutter: `v1.12.13+hotfix.9` ，库: `0.1.2 `：正常
Flutter: `1.22.6` ，库: `0.2 ` ：安卓正常， iOS 没有模糊背景直接透明看到背景

测试设备：
- 模拟器`iPhone 11`
- 真机`iPhone6`
- 真机`iPhone11`

**Comment by AlexV525** [comment]
https://github.com/fluttercandies/ripple_backdrop_animate_route/blob/a19020641e3831e6f6d71ddb236ceb3c4cfc2374/lib/src/ripple_backdrop_animation.dart#L186

将这一行的空格文字替换为「　」（全角空格）即可。旧版本没办法升级，只能本地修改。
